/**
 * types.tsx
 */

export const Types = {
    // LOGIN
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    GOTO_LOGOUT: "GOTO_LOGOUT",
    GOTO_SIGNUP: "GOTO_SIGNUP",
    GOTO_HOME: "GOTO_HOME",
    GOTO_VERIFICATION: "GOTO_VERIFICATION"
};
