/**
 * types.tsx
 */

export const Types = {
    // INIT APP
    INIT_APP_ENTRY: "INIT_APP_ENTRY",

    // ON WILL MOUNT
    INIT_WILL_MOUNT: "INIT_WILL_MOUNT",
    RUN_WILL_MOUNT_SUCCESS: "RUN_WILL_MOUNT_SUCCESS",
    RUN_WILL_MOUNT_FAIL: "RUN_WILL_MOUNT_FAIL",

    // ON DID MOUNT
    INIT_DID_MOUNT: "INIT_DID_MOUNT",
    RUN_DID_MOUNT_SUCCESS: "RUN_DID_MOUNT_SUCCESS",
    RUN_DID_MOUNT_FAIL: "RUN_DID_MOUNT_FAIL",

    // UPDATE DEVICE READY
    UPDATE_DEVICE_READY: "UPDATE_DEVICE_READY"

};
