/**
 * types.tsx
 */

export const Types = {
    // VERIFY
    VERIFY: "VERIFY",
    VERIFICATION_SUCCESS: "VERIFICATION_SUCCESS",
    VERIFICATION_FAIL: "VERIFICATION_FAIL",
    RESEND_CODE: "RESEND_CODE",
    RESEND_CODE_SUCCESS: "RESEND_CODE_SUCCESS",
    RESEND_CODE_FAIL: "RESEND_CODE_FAIL",
    GOTO_SIGNUP: "GOTO_SIGNUP"
};
