/**
 * types.tsx
 */

export const Types = {
    // CASE BUILDER
    BUILD_CASE_LAYOUT: "BUILD_CASE_LAYOUT",
    BUILD_CASE_LAYOUT_SUCCESS: "BUILD_CASE_LAYOUT_SUCCESS",
    BUILD_CASE_LAYOUT_FAIL: "BUILD_CASE_LAYOUT_FAIL",

    // SUBMIT CASE
    SUBMIT_CASE: "SUBMIT_CASE",
    SUBMIT_CASE_SUCCESS: "SUBMIT_CASE_SUCCESS",
    SUBMIT_CASE_FAIL: "SUBMIT_CASE_FAIL",

    GOTO_BUILD_CASE: "GOTO_BUILD_CASE",
    GOTO_TREATMENT_PLAN: "GOTO_TREATMENT_PLAN",

    // UPDATE SHOW/HIDE QUESTIONS
    UPDATE_QUESTION_VISIBILITY: "UPDATE_QUESTION_VISIBILITY"
};
