/**
 * types.tsx
 */

export const Types = {
    // AUTHENTICATION
    AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
    UPDATE_AUTHENTICATION_CREDENTIALS: "UPDATE_AUTHENTICATION_CREDENTIALS",
    UPDATE_AUTHENTICATION_TOKEN: "UPDATE_AUTHENTICATION_TOKEN"
};
