/**
 * types.tsx
 */

 export const Types = {
    // SIGNUP
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
    CREATE_ACCOUNT_FAIL: "CREATE_ACCOUNT_FAIL",
    GOTO_LOGIN: "GOTO_LOGIN",
    GOTO_VERIFICATION: "GOTO_VERIFICATION",
    GOTO_TERMS_AND_CONDITIONS: "GOTO_TERMS_AND_CONDITIONS"

};
